# Generated by Django 4.2.13 on 2024-07-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iskierek_site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("książka", "literacki"),
                            ("dyskusja", "dyskusyjny"),
                            ("sport", "sportów rekreacyjnych"),
                            ("zwierzę", "miłośników zwierząt"),
                            ("astrologia", "astrologiczny"),
                            ("robot", "robotyczny"),
                            ("wycieczka", "wycieczkowo-survivalowy"),
                            ("film", "filmowy"),
                            ("zielę", "zielników"),
                            ("gra", "miłośnicy gier"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "special",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p1", "przewodnicząca"),
                            ("p2", "przewodniczący"),
                            ("p3", "przewodniczące"),
                            ("o1", "opiekunka"),
                            ("o2", "opiekun"),
                            ("o3", "opiekuńcze"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Extracurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("chór", "chór uniwersytecki"),
                            ("gazetka", 'gazeta "Głos Młodego Miasta"'),
                            ("moda", "koło modowe"),
                            ("gospodynie", "koło praktycznych umiejętności"),
                            ("teatr", "koło teatralne"),
                            ("wolontariat", "wolontariat"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "special",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p1", "przewodnicząca"),
                            ("p2", "przewodniczący"),
                            ("p3", "przewodniczące"),
                            ("o1", "opiekunka"),
                            ("o2", "opiekun"),
                            ("o3", "opiekuńcze"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("eko", "ekonomia"),
                            ("log", "logistyka"),
                            ("rif", "rachunkowość i finanse"),
                            ("zar", "zarządzanie"),
                            ("his", "historia"),
                            ("tur", "turystyka"),
                            ("lin", "lingwistyka"),
                            ("arc", "archeologia"),
                            ("pie", "pielęgniarstwo"),
                            ("dif", "dietetyka i fizjoterapia"),
                            ("kos", "kosmetologia"),
                            ("rat", "ratownictwo medyczne"),
                            ("air", "automatyka i robotyka"),
                            ("now", "nowe technologie"),
                            ("ach", "architektura"),
                            ("mat", "materiałoznawstwo"),
                            ("aif", "astronomia i fizyka"),
                            ("inf", "informatyka"),
                            ("mat", "matematyka"),
                            ("che", "chemia"),
                            ("zie", "zielone technologia"),
                            ("geo", "geodezja"),
                            ("wet", "weterynaria"),
                            ("bio", "biologia"),
                            ("akt", "aktorstwo"),
                            ("tec", "techniki artystyczne"),
                            ("muz", "muzyka"),
                            ("tiu", "tkaniny i ubiór"),
                            ("pra", "prawo"),
                            ("kry", "kryminologia"),
                            ("oiw", "obrona i wojskowość"),
                            ("adm", "administracja"),
                            ("ped", "pedagogika"),
                            ("psy", "psychologia"),
                            ("soc", "socjologia"),
                            ("pol", "politologia"),
                            ("niż", "nauka o iskrach i żywiołach"),
                            ("gen", "genetyka uiskrzonych"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("e-b", "Ekonomiczno-Biznesowy"),
                            ("med", "Medyczny"),
                            ("hum", "Humanistyczny"),
                            ("tec", "Techniczny"),
                            ("ści", "Nauk Ścisłych"),
                            ("prz", "Przyrodniczy"),
                            ("art", "Artystyczny"),
                            ("pia", "Prawa i Administracji"),
                            ("nsp", "Nauk Społecznych"),
                            ("isk", "Iskier"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1", "I"),
                            ("2", "II"),
                            ("3", "III"),
                            ("4", "IV"),
                            ("5", "V"),
                            ("d1", "doktorat, I"),
                            ("d2", "doktorat, II"),
                            ("d3", "doktorat, III"),
                            ("a1", "absolwentka"),
                            ("a2", "absolwent"),
                            ("a3", "absolwencie"),
                            ("w1", "wykładowczyni"),
                            ("w2", "wykładowca"),
                            ("w3", "wykładowcze"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("AND", "Andromedy"),
                            ("AUR", "Aurigi"),
                            ("CSS", "Cassiopei"),
                            ("CAS", "Castora"),
                            ("CET", "Cetusa"),
                            ("ERI", "Eridanusa"),
                            ("HYD", "Hydrusa"),
                            ("LYN", "Lynx"),
                            ("MON", "Monocerosa"),
                            ("ORI", "Oriona"),
                            ("POL", "Polaris"),
                            ("SER", "Serpensa"),
                            ("SIR", "Siriusa"),
                            ("VOL", "Volansa"),
                            ("ANT", "Antaresa"),
                            ("BEL", "Bellatrix"),
                            ("COR", "Corvusa"),
                            ("DRA", "Draco"),
                            ("OCT", "Octans"),
                            ("PLL", "Polluxa"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "rarity",
                    models.IntegerField(
                        choices=[(1, "unikatowa"), (2, "rzadka"), (3, "unikatowa")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("łuk", "łucznictwo"),
                            ("hojek", "hokej"),
                            ("basen", "basen"),
                            ("siatka", "siatkówka"),
                            ("kosz", "koszykówka"),
                            ("boks", "boks"),
                            ("taniec", "taniec"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "special",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p1", "kapitan"),
                            ("p2", "kapitanka"),
                            ("p3", "kapitańcze"),
                            ("o1", "trenerka"),
                            ("o2", "trener"),
                            ("o3", "trenerze"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                ("dob", models.DateField()),
                (
                    "element",
                    models.CharField(
                        choices=[
                            ("O", "ogień"),
                            ("E", "elektryczność"),
                            ("P", "powietrze"),
                            ("Z", "ziemia"),
                            ("W", "woda"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "living",
                    models.CharField(
                        choices=[
                            ("AP", "akademik Pyxis"),
                            ("AL", "akademik Lyra"),
                            ("AC", "akademik Crux"),
                            ("DM", "dom w Brightway"),
                            ("MM", "mieszkanie w Brightway"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iskierek_site.club",
                    ),
                ),
                (
                    "extracurricular",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iskierek_site.extracurricular",
                    ),
                ),
                (
                    "spark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iskierek_site.spark",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iskierek_site.sport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iskierek_site.discorduser",
                    ),
                ),
            ],
        ),
    ]
