# Generated by Django 4.2.13 on 2024-07-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iskierek_site", "0002_club_extracurricular_major_spark_sport_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="name",
            field=models.CharField(
                choices=[
                    ("eko", "ekonomia"),
                    ("log", "logistyka"),
                    ("rif", "rachunkowość i finanse"),
                    ("zar", "zarządzanie"),
                    ("his", "historia"),
                    ("tur", "turystyka"),
                    ("lin", "lingwistyka"),
                    ("arc", "archeologia"),
                    ("pie", "pielęgniarstwo"),
                    ("dif", "dietetyka i fizjoterapia"),
                    ("kos", "kosmetologia"),
                    ("rat", "ratownictwo medyczne"),
                    ("air", "automatyka i robotyka"),
                    ("now", "nowe technologie"),
                    ("ach", "architektura"),
                    ("mat", "materiałoznawstwo"),
                    ("aif", "astronomia i fizyka"),
                    ("inf", "informatyka"),
                    ("mtm", "matematyka"),
                    ("che", "chemia"),
                    ("zie", "zielone technologia"),
                    ("geo", "geodezja"),
                    ("wet", "weterynaria"),
                    ("bio", "biologia"),
                    ("akt", "aktorstwo"),
                    ("tec", "techniki artystyczne"),
                    ("muz", "muzyka"),
                    ("tiu", "tkaniny i ubiór"),
                    ("pra", "prawo"),
                    ("kry", "kryminologia"),
                    ("oiw", "obrona i wojskowość"),
                    ("adm", "administracja"),
                    ("ped", "pedagogika"),
                    ("psy", "psychologia"),
                    ("soc", "socjologia"),
                    ("pol", "politologia"),
                    ("niż", "nauka o iskrach i żywiołach"),
                    ("gen", "genetyka uiskrzonych"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="spark",
            name="rarity",
            field=models.IntegerField(
                choices=[(1, "powszechna"), (2, "rzadka"), (3, "unikatowa")]
            ),
        ),
    ]
