# Generated by Django 4.2.13 on 2024-07-13 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iskierek_site", "0003_alter_major_name_alter_spark_rarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="iskierek_site.major",
            ),
            preserve_default=False,
        ),
    ]
