# Generated by Django 4.2.13 on 2024-07-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iskierek_site",
            "0005_student_faculty_student_year_alter_student_major_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default=None, max_length=125),
            preserve_default=False,
        ),
    ]
