# Generated by Django 4.2.13 on 2024-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iskierek_site",
            "0007_alter_student_club_alter_student_extracurricular_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.CharField(
                choices=[
                    ("1", "I rok"),
                    ("2", "II rok"),
                    ("3", "III rok"),
                    ("4", "IV rok"),
                    ("5", "V rok"),
                    ("d1", "doktorat, I rok"),
                    ("d2", "doktorat, II rok"),
                    ("d3", "doktorat, III rok"),
                    ("a1", "absolwentka"),
                    ("a2", "absolwent"),
                    ("a3", "absolwencie"),
                    ("w1", "wykładowczyni"),
                    ("w2", "wykładowca"),
                    ("w3", "wykładowcze"),
                ],
                max_length=2,
            ),
        ),
    ]
