# Generated by Django 4.2.13 on 2024-07-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iskierek_site",
            "0010_alter_professor_dorm_alter_professor_faculty2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="dorm_special",
            field=models.CharField(
                blank=True,
                choices=[
                    ("z1", "zarządczyni"),
                    ("z2", "zarządca"),
                    ("z3", "zarządcze"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
